# Generated by Django 5.1.6 on 2025-04-13 11:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ue',
            fields=[
                ('id_UEs', models.AutoField(primary_key=True, serialize=False)),
                ('code_UEs', models.CharField(max_length=50, unique=True)),
                ('intitule_UEs', models.CharField(max_length=255)),
                ('id_prof', models.ForeignKey(db_column='id_prof', on_delete=django.db.models.deletion.CASCADE, to='accounts.professeur')),
            ],
            options={
                'db_table': 'UEs',
            },
        ),
        migrations.CreateModel(
            name='Fichier_Ue',
            fields=[
                ('id_Fichiers_Ue', models.AutoField(primary_key=True, serialize=False)),
                ('lien_fichier', models.FileField(upload_to='fichiers_ue/')),
                ('id_UEs', models.ForeignKey(db_column='id_UEs', on_delete=django.db.models.deletion.CASCADE, to='ues.ue')),
            ],
            options={
                'db_table': 'Fichiers_Ue',
            },
        ),
    ]
