# Generated by Django 5.1.6 on 2025-08-21 20:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classe',
            fields=[
                ('id_classe', models.AutoField(primary_key=True, serialize=False)),
                ('nom_licence', models.CharField(max_length=100)),
                ('niveau', models.CharField(max_length=50)),
                ('departement', models.CharField(choices=[('GC', 'Génie Civil'), ('GE', 'Génie Electrique'), ('GM', 'Génie Mécanique'), ('GI', 'Génie Informatique'), ('TC', 'Tronc Commun')], max_length=100)),
                ('mention', models.CharField(choices=[('LF', 'Licence Fondamentale'), ('LP', 'Licence Professionelle')], max_length=23)),
            ],
            options={
                'verbose_name': 'classe',
                'verbose_name_plural': 'classes',
                'db_table': 'classe',
                'ordering': ['-mention'],
            },
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True)),
                ('nom', models.CharField(max_length=150)),
                ('prenom', models.CharField(max_length=150)),
                ('role', models.CharField(choices=[('professeur', 'professeur'), ('secretaire_general', 'sécrétaire général'), ('secretaire_classe', 'sécrétaire de classe'), ('admin', 'admin')], db_index=True, max_length=23)),
                ('auth_provider', models.CharField(default='email', max_length=10)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('is_staff', models.BooleanField(db_index=True, default=False)),
                ('is_verified', models.BooleanField(db_index=True, default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'utilisateur',
                'ordering': ['role'],
            },
        ),
        migrations.CreateModel(
            name='Professeur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signature', models.ImageField(blank=True, null=True, upload_to='signatures/')),
                ('user_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'professeur',
                'verbose_name_plural': 'professeurs',
                'db_table': 'professeur',
                'ordering': ['-user_id'],
            },
        ),
        migrations.CreateModel(
            name='SecretaireClasse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_classe', models.ForeignKey(blank=True, db_column='id_classe', null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.classe')),
                ('user_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'secretaireclasse',
            },
        ),
        migrations.CreateModel(
            name='Cahiertexte',
            fields=[
                ('id_cahier', models.AutoField(primary_key=True, serialize=False)),
                ('date_de_creation', models.DateTimeField(auto_now_add=True)),
                ('date_de_mise_a_jour', models.DateTimeField(auto_now=True)),
                ('id_classe', models.ForeignKey(db_column='id_classe', on_delete=django.db.models.deletion.CASCADE, to='accounts.classe')),
                ('id_secretaire', models.ForeignKey(db_column='id_secretaire', on_delete=django.db.models.deletion.CASCADE, to='accounts.secretaireclasse')),
            ],
            options={
                'verbose_name': 'Cahiertexte',
                'verbose_name_plural': 'Cahiertextes',
                'db_table': 'cahiertexte',
                'ordering': ['-date_de_creation'],
            },
        ),
        migrations.CreateModel(
            name='SecretaireGeneral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departement', models.CharField(choices=[('Génie_Civil', 'Génie Civil'), ('Génie_Electrique', 'Génie Electrique'), ('Génie_Mécanique', 'Génie Mécanique'), ('Génie_Informatique', 'Génie Informatique')], max_length=100)),
                ('user_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'secretairegeneral',
            },
        ),
        migrations.CreateModel(
            name='Ue',
            fields=[
                ('id_UEs', models.AutoField(primary_key=True, serialize=False)),
                ('code_UEs', models.CharField(db_index=True, max_length=50, unique=True)),
                ('intitule_UEs', models.CharField(max_length=255)),
                ('crenaux', models.JSONField(default=dict)),
                ('classe', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.classe')),
                ('id_prof', models.ForeignKey(db_column='id_prof', null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.professeur')),
            ],
            options={
                'verbose_name': 'ue',
                'verbose_name_plural': 'ues',
                'db_table': 'ues',
                'ordering': ['-classe'],
            },
        ),
        migrations.CreateModel(
            name='Seance',
            fields=[
                ('id_seance', models.AutoField(primary_key=True, serialize=False)),
                ('sous_session_seance', models.CharField(max_length=1000)),
                ('date_heure', models.DateTimeField(db_index=True)),
                ('id_classe', models.ForeignKey(blank=True, db_column='id_classe', null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.classe')),
                ('id_professeur', models.ForeignKey(blank=True, db_column='id_professeur', null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.professeur')),
                ('id_ues', models.ForeignKey(db_column='id_UEs', on_delete=django.db.models.deletion.CASCADE, to='accounts.ue')),
            ],
            options={
                'db_table': 'seance',
            },
        ),
        migrations.CreateModel(
            name='Fichier_Ue',
            fields=[
                ('id_Fichiers_Ue', models.AutoField(primary_key=True, serialize=False)),
                ('lien_fichier', models.FileField(upload_to='fichiers_ue/')),
                ('id_UEs', models.ForeignKey(db_column='id_UEs', on_delete=django.db.models.deletion.CASCADE, to='accounts.ue')),
            ],
            options={
                'db_table': 'fichiers_ue',
                'ordering': ['-id_UEs'],
            },
        ),
        migrations.CreateModel(
            name='Validation',
            fields=[
                ('id_validation', models.AutoField(primary_key=True, serialize=False)),
                ('statut', models.CharField(choices=[('valide', 'validé'), ('non_valide', 'non validé')], db_index=True, max_length=11)),
                ('date_validation', models.DateTimeField()),
                ('id_cahier', models.ForeignKey(db_column='id_cahier', on_delete=django.db.models.deletion.CASCADE, to='accounts.cahiertexte')),
                ('id_professeur', models.ForeignKey(db_column='id_professeur', on_delete=django.db.models.deletion.CASCADE, to='accounts.professeur')),
                ('id_seance', models.ForeignKey(db_column='id_seance', on_delete=django.db.models.deletion.CASCADE, to='accounts.seance')),
                ('id_ues', models.ForeignKey(db_column='id_UEs', on_delete=django.db.models.deletion.CASCADE, to='accounts.ue')),
            ],
            options={
                'db_table': 'validation',
            },
        ),
    ]
