# Generated by Django 5.1.6 on 2025-07-30 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="classe",
            options={
                "ordering": ["-mention"],
                "verbose_name": "classe",
                "verbose_name_plural": "classes",
            },
        ),
        migrations.AlterModelOptions(
            name="customuser",
            options={"ordering": ["role"]},
        ),
        migrations.AlterModelOptions(
            name="professeur",
            options={
                "ordering": ["-user_id"],
                "verbose_name": "professeur",
                "verbose_name_plural": "professeurs",
            },
        ),
        migrations.AlterField(
            model_name="classe",
            name="departement",
            field=models.CharField(
                choices=[
                    ("GC", "Génie Civil"),
                    ("GE", "Génie Electrique"),
                    ("GM", "Génie Mécanique"),
                    ("GI", "Génie Informatique"),
                    ("TC", "Tronc Commun"),
                ],
                max_length=100,
            ),
        ),
    ]
