# Generated by Django 5.1.6 on 2025-04-13 11:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CahierDeTexte', '0002_seance_id_ues_validation_id_ues'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='secretaireclasse',
            name='id_classe',
            field=models.ForeignKey(blank=True, db_column='id_classe', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='CahierDeTexte.classe'),
        ),
    ]
