# Generated by Django 5.1.6 on 2025-10-22 19:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cahiertexte',
            name='id_classe',
            field=models.ForeignKey(db_column='id_classe', on_delete=django.db.models.deletion.CASCADE, to='accounts.classe', unique=True),
        ),
    ]
