# Generated by Django 5.1.6 on 2025-10-22 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_cahiertexte_id_classe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='validation',
            name='date_validation',
            field=models.DateTimeField(null=True),
        ),
    ]
