# Generated by Django 5.1.6 on 2025-08-23 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_customuser_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='secretairegeneral',
            name='departement',
            field=models.CharField(choices=[('GC', 'Génie Civil'), ('GE', 'Génie Electrique'), ('GM', 'Génie Mécanique'), ('GI', 'Génie Informatique')], max_length=100),
        ),
    ]
