# Generated by Django 5.1.6 on 2025-04-13 11:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classe',
            fields=[
                ('id_classe', models.AutoField(primary_key=True, serialize=False)),
                ('nom_licence', models.CharField(max_length=100)),
                ('niveau', models.CharField(max_length=50)),
                ('departement', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'classe',
            },
        ),
        migrations.CreateModel(
            name='Cahiertexte',
            fields=[
                ('id_cahier', models.AutoField(primary_key=True, serialize=False)),
                ('date_de_creation', models.DateTimeField(auto_now_add=True)),
                ('date_de_mise_a_jour', models.DateTimeField(auto_now_add=True)),
                ('id_secretaire', models.ForeignKey(db_column='id_secretaire', on_delete=django.db.models.deletion.CASCADE, to='accounts.secretaireclasse')),
                ('id_classe', models.ForeignKey(db_column='id_classe', on_delete=django.db.models.deletion.CASCADE, to='CahierDeTexte.classe')),
            ],
            options={
                'verbose_name': 'Cahiertexte',
                'verbose_name_plural': 'Cahiertextes',
                'db_table': 'Cahiertexte',
                'ordering': ['-date_de_creation'],
            },
        ),
        migrations.CreateModel(
            name='Seance',
            fields=[
                ('id_seance', models.AutoField(primary_key=True, serialize=False)),
                ('date_heure', models.DateTimeField()),
                ('id_classe', models.ForeignKey(blank=True, db_column='id_classe', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='CahierDeTexte.classe')),
                ('id_professeur', models.ForeignKey(blank=True, db_column='id_professeur', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.professeur')),
            ],
            options={
                'db_table': 'seance',
            },
        ),
        migrations.CreateModel(
            name='Validation',
            fields=[
                ('id_validation', models.AutoField(primary_key=True, serialize=False)),
                ('statut', models.CharField(choices=[('valide', 'validé'), ('non_valide', 'non validé')], max_length=11)),
                ('date_validation', models.DateTimeField()),
                ('signature', models.ImageField(blank=True, null=True, upload_to='validations/')),
                ('id_cahier', models.ForeignKey(blank=True, db_column='id_cahier', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='CahierDeTexte.cahiertexte')),
                ('id_professeur', models.ForeignKey(blank=True, db_column='id_professeur', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.professeur')),
                ('id_seance', models.ForeignKey(blank=True, db_column='id_seance', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='CahierDeTexte.seance')),
            ],
            options={
                'db_table': 'validation',
            },
        ),
    ]
