# Generated by Django 5.1.6 on 2025-04-13 11:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CahierDeTexte', '0001_initial'),
        ('ues', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='seance',
            name='id_ues',
            field=models.ForeignKey(blank=True, db_column='id_UEs', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ues.ue'),
        ),
        migrations.AddField(
            model_name='validation',
            name='id_ues',
            field=models.ForeignKey(blank=True, db_column='id_UEs', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ues.ue'),
        ),
    ]
